### ISSUE TITLE
Facebook PHP SDK 4 support?

### ISSUE THREAD

**Issue by m-vdv** [gonzalo123/SilexFacebookLogin#1]
Hi Gonzalo

I'm wondering if this going to be upgraded to support the latest Facebook SDK (version 4)?
Have been looking for an easy way to integrate Facebook into my Silex project, this could be it.

Please let me know!

Thanks

**Comment by gonzalo123** [comment]
Hi have read the documentation for SDK this weekend at a glance and I also have tried to use it. It's a bit nightmare. The documentation is very confused. My first tests didn't succeed. I don't have any project that needs this SDK, so it looks like I'm not going to support soon :(.

**Comment by m-vdv** [comment]
Thanks for looking into it @gonzalo123
I've tried integrating the SDK as well last weekend and have run into lot's of issues too..
Right now I'm only making API calls to the Facebook Graph which is quite easy and working well.
Still need to find out how to integrate Facebook Login and personal Graph API calls.

If anyone has a tutorial or service provider, please let me know!

**Comment by gonzalo123** [comment]
Have you got any example of api calls (one gist for example)? 
In my tests I can login successfully, but in a logged session I cannot perform any api call (for example to retrieve the name of the user). The documentation is a nightmare. It looks like library is various steps fordward the doc and examples doesn't work.

**Comment by m-vdv** [comment]
I'm simply calling the Facebook Graph API directly (no PHP SDK needed)
Example:
https://graph.facebook.com/v2.2/733873679993839?fields=id,name&access_token=$APP_ID|$APP_SECRET

However this does only work for calls that don't require a user session.

I've also played around with the PHP SDK Following tutorials like this one:
https://www.webniraj.com/2014/05/01/facebook-api-php-sdk-updated-to-v4-0-0/
and...
http://www.benmarshall.me/facebook-sdk-php-v4/
http://metah.ch/blog/2014/05/facebook-sdk-4-0-0-for-php-a-working-sample-to-get-started/
https://www.apptic.me/blog/simple-facebook-php-sdk-4-tutorial.php

Using the code in these tutorials works to login and get the users data.
I struggled to adjust to code to be extendable and nicely integrated within my Silex project which uses the Silex Kitchen Edition (https://github.com/lyrixx/Silex-Kitchen-Edition) as base.

If you play around with it in a silex project you'll probably run into a session already started issue, add this to your .htaccess to fix it:
php_flag session.auto_start 0

Facebook also made a nice tool to explore the Graph here: https://developers.facebook.com/tools/explorer/

Unfortunately there is no working Silex + Facebook SDK 4 example anywhere, we need this!
